site_name: Simtestlab
site_url: https://your-site-url.com
site_description: Complete documentation for simtestlab
docs_dir: simtestlab
nav:
  - Home: index.md
  - Help: help.md
  - GitHub Issues:
      - Overview: github_issues/overview/index.md
      - Repositories:
          - ADBMSproj: github_issues/repositories/ADBMSproj/index.md
          - BESS_BMS: github_issues/repositories/BESS_BMS/index.md
          - BESS_tools: github_issues/repositories/BESS_tools/index.md
          - BMS_Algorithm: github_issues/repositories/BMS_Algorithm/index.md
          - Battery-Chamber-Design: github_issues/repositories/Battery-Chamber-Design/index.md
          - Bhima: github_issues/repositories/Bhima/index.md
          - Button_interface: github_issues/repositories/Button_interface/index.md
          - Cell_Emulator: github_issues/repositories/Cell_Emulator/index.md
          - Chamber-Automation-Board: github_issues/repositories/Chamber-Automation-Board/index.md
          - Chamber-Automation-Firmware: github_issues/repositories/Chamber-Automation-Firmware/index.md
          - DESVIAR: github_issues/repositories/DESVIAR/index.md
          - DaveProj: github_issues/repositories/DaveProj/index.md
          - Documentations: github_issues/repositories/Documentations/index.md
          - Enclosure-for-XMC4800: github_issues/repositories/Enclosure-for-XMC4800/index.md
          - EtherCAT: github_issues/repositories/EtherCAT/index.md
          - FPGA: github_issues/repositories/FPGA/index.md
          - GTest_Jenkins: github_issues/repositories/GTest_Jenkins/index.md
          - Generic-IO-Board: github_issues/repositories/Generic-IO-Board/index.md
          - HIL: github_issues/repositories/HIL/index.md
          - Matlab_C_Deploy_in-STM32: github_issues/repositories/Matlab_C_Deploy_in-STM32/index.md
          - MiniHIL: github_issues/repositories/MiniHIL/index.md
          - NGS_Bioinformatics: github_issues/repositories/NGS_Bioinformatics/index.md
          - Panther_30A16C: github_issues/repositories/Panther_30A16C/index.md
          - Panther_30A8C: github_issues/repositories/Panther_30A8C/index.md
          - PieShop.InventoryManagement: github_issues/repositories/PieShop.InventoryManagement/index.md
          - RelayX-16: github_issues/repositories/RelayX-16/index.md
          - Resolver_Enclosure: github_issues/repositories/Resolver_Enclosure/index.md
          - SOEM_Master_Beckhoff_EtherCAT_Slaves: github_issues/repositories/SOEM_Master_Beckhoff_EtherCAT_Slaves/index.md
          - SOEM_XMC4800_EtherCAT_Communication: github_issues/repositories/SOEM_XMC4800_EtherCAT_Communication/index.md
          - STL001: github_issues/repositories/STL001/index.md
          - STL002: github_issues/repositories/STL002/index.md
          - Sphinx_Documentation: github_issues/repositories/Sphinx_Documentation/index.md
          - TestEnv: github_issues/repositories/TestEnv/index.md
          - UDS-Protocol-Implementation: github_issues/repositories/UDS-Protocol-Implementation/index.md
          - VitaTest: github_issues/repositories/VitaTest/index.md
          - XCP-Protocol: github_issues/repositories/XCP-Protocol/index.md
          - XMC-Makefile-Generator: github_issues/repositories/XMC-Makefile-Generator/index.md
          - XMC4800-_PIGGY_HAT: github_issues/repositories/XMC4800-_PIGGY_HAT/index.md
          - XMC4800_FreeRTOS_Tutorial: github_issues/repositories/XMC4800_FreeRTOS_Tutorial/index.md
          - XMC4800_Iot_Kit: github_issues/repositories/XMC4800_Iot_Kit/index.md
          - adbms: github_issues/repositories/adbms/index.md
          - adbms_master: github_issues/repositories/adbms_master/index.md
          - adbms_master_slave: github_issues/repositories/adbms_master_slave/index.md
          - adbms_slave: github_issues/repositories/adbms_slave/index.md
          - admin_task: github_issues/repositories/admin_task/index.md
          - atlas: github_issues/repositories/atlas/index.md
          - attendance_app: github_issues/repositories/attendance_app/index.md
          - bio_technology: github_issues/repositories/bio_technology/index.md
          - bms_app: github_issues/repositories/bms_app/index.md
          - bms_bsw: github_issues/repositories/bms_bsw/index.md
          - bms_master: github_issues/repositories/bms_master/index.md
          - bms_unit_test: github_issues/repositories/bms_unit_test/index.md
          - bms_web: github_issues/repositories/bms_web/index.md
          - c-test-tool: github_issues/repositories/c-test-tool/index.md
          - cantex_cpp: github_issues/repositories/cantex_cpp/index.md
          - cat_embedded: github_issues/repositories/cat_embedded/index.md
          - chamber_pilot: github_issues/repositories/chamber_pilot/index.md
          - chat_app: github_issues/repositories/chat_app/index.md
          - common-tasks: github_issues/repositories/common-tasks/index.md
          - cpp_projects: github_issues/repositories/cpp_projects/index.md
          - dearpygui: github_issues/repositories/dearpygui/index.md
          - demo_todo: github_issues/repositories/demo_todo/index.md
          - development_tasks: github_issues/repositories/development_tasks/index.md
          - devops_pro: github_issues/repositories/devops_pro/index.md
          - e-trq: github_issues/repositories/e-trq/index.md
          - eCal: github_issues/repositories/eCal/index.md
          - eChatBot: github_issues/repositories/eChatBot/index.md
          - ecal_backend: github_issues/repositories/ecal_backend/index.md
          - ecal_frontend: github_issues/repositories/ecal_frontend/index.md
          - echo_gecko_backend: github_issues/repositories/echo_gecko_backend/index.md
          - echo_gecko_ui: github_issues/repositories/echo_gecko_ui/index.md
          - esimEngine: github_issues/repositories/esimEngine/index.md
          - esimtest: github_issues/repositories/esimtest/index.md
          - esimtest_pro: github_issues/repositories/esimtest_pro/index.md
          - esysflow: github_issues/repositories/esysflow/index.md
          - esysflow-feature: github_issues/repositories/esysflow-feature/index.md
          - esysflowQt: github_issues/repositories/esysflowQt/index.md
          - esysflow_backend: github_issues/repositories/esysflow_backend/index.md
          - esysflow_wrapper: github_issues/repositories/esysflow_wrapper/index.md
          - expense_tracker: github_issues/repositories/expense_tracker/index.md
          - favorite_place: github_issues/repositories/favorite_place/index.md
          - flu_detector_tech: github_issues/repositories/flu_detector_tech/index.md
          - flutter_dev: github_issues/repositories/flutter_dev/index.md
          - hardware: github_issues/repositories/hardware/index.md
          - imgui: github_issues/repositories/imgui/index.md
          - jmk-website: github_issues/repositories/jmk-website/index.md
          - leopard: github_issues/repositories/leopard/index.md
          - liger: github_issues/repositories/liger/index.md
          - matlab_learning: github_issues/repositories/matlab_learning/index.md
          - meal_app: github_issues/repositories/meal_app/index.md
          - mechanical_design: github_issues/repositories/mechanical_design/index.md
          - node_editor: github_issues/repositories/node_editor/index.md
          - python_qvaser: github_issues/repositories/python_qvaser/index.md
          - qt_bms_gui: github_issues/repositories/qt_bms_gui/index.md
          - qt_can_kvaser: github_issues/repositories/qt_can_kvaser/index.md
          - qt_example: github_issues/repositories/qt_example/index.md
          - r_programming: github_issues/repositories/r_programming/index.md
          - redmine_documentation_images: github_issues/repositories/redmine_documentation_images/index.md
          - resolver: github_issues/repositories/resolver/index.md
          - shopping_list: github_issues/repositories/shopping_list/index.md
          - simtestlab_backend: github_issues/repositories/simtestlab_backend/index.md
          - simtestlab_website: github_issues/repositories/simtestlab_website/index.md
          - software_license_model: github_issues/repositories/software_license_model/index.md
          - stl_automation_scripts: github_issues/repositories/stl_automation_scripts/index.md
          - stl_production_pipelines: github_issues/repositories/stl_production_pipelines/index.md
          - tree_life: github_issues/repositories/tree_life/index.md
          - trust-website: github_issues/repositories/trust-website/index.md
          - vinay_learning_mil_sil: github_issues/repositories/vinay_learning_mil_sil/index.md
          - xwiki_documentation: github_issues/repositories/xwiki_documentation/index.md
          - ymer_pro: github_issues/repositories/ymer_pro/index.md
  - Project Manager: 
      - ... | ProjectManagement/**
  - BMS Application:
      - ... | SoftwareSpecifiactions/ApplicationSoftware/**
  - System Engineering: 
      - ... | System Engineering/**
theme:
  name: material
  custom_dir: simtestlab/custom_theme
  font:
    text: Merriweather Sans
    code: "Fira Code, Menlo, Monaco, Consolas, monospace"
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - content.grid 
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: grey
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: [docs]
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
      inline_syntax:
        - dollar
        - round
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - toc:
      toc_depth: 0

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js
  - javascripts/github-filters.js



plugins:
  - search
  - awesome-pages
  - blog
  - charts
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true

copyright: Copyright &copy; 2020-2025 by Simtestlab Sweden AB

extra:
  generator: false
  comments: false
  status:
    draft: In draft
    review: In review
    approved: Approved
    deprecated: Deprecated
  icons:
    header:
      - icon: material/help-circle
        link: help/
        name: Help

extra_css:
  - styles/extra.css

