site_name: Simtestlab
site_url: https://your-site-url.com
site_description: Complete documentation for simtestlab
docs_dir: simtestlab
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - Project Manager: 
      - ... | ProjectManagement/**
  - BMS Application:
      - ... | bms_software/Specifications/**
theme:
  name: material
  custom_dir: simtestlab/custom_theme
  font:
    text: Merriweather Sans
    code: "Fira Code, Menlo, Monaco, Consolas, monospace"
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: [docs]
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
      inline_syntax:
        - dollar
        - round
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - toc:
      toc_depth: 0

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - awesome-pages
  - blog
  - charts
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true

copyright: Copyright &copy; 2020-2025 by Simtestlab Sweden AB

extra:
  generator: false
  comments: true
  status:
    draft: In draft
    review: In review
    approved: Approved
    deprecated: Deprecated

