[build]
  # Directory to run the build command
  base = "."
  
  # Build command (fallback if not using GitHub Actions)
  command = "pip install -r requirements.txt && mkdocs build"
  
  # Directory with the static files for deployment (MkDocs output)
  publish = "site"

[build.environment]
  # Python version to use
  PYTHON_VERSION = "3.10"

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self'"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (if needed)
# [build.environment]
#   NODE_VERSION = "18"
#   HUGO_VERSION = "0.101.0"