name: Deploy MkDocs to Netlify via Repo B

on:
  push:
    branches:
      - mkdocs-enabled-submodules-added  # your branch in Repo A

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repo A with recursive submodules
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.ORG_TOKEN }}   # allows access to private submodules

      # 2️⃣ Optional: Preserve Netlify config from Repo B
      - name: Preserve Netlify Config
        run: |
          echo "Attempting to preserve Netlify config from target repo..."
          if git clone https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/simtestlab-se/atlas_deploy.git temp_repo 2>/dev/null; then
            echo "Successfully cloned target repo"
            if [ -f "temp_repo/netlify.toml" ]; then
              cp temp_repo/netlify.toml . 
              echo "Preserved netlify.toml"
            fi
            if [ -f "temp_repo/_redirects" ]; then
              cp temp_repo/_redirects .
              echo "Preserved _redirects"
            fi
            rm -rf temp_repo
          else
            echo "Target repo doesn't exist or is empty, skipping config preservation"
          fi

      # 3️⃣ Set up Python (for MkDocs build)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Build MkDocs site
      - name: Build MkDocs
        run: mkdocs build

      # 6️⃣ Push snapshot to Repo B
      - name: Push to Repo B
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch main

          rm -rf .git
          git init
          git add .
          git commit -m "Mirror from atlas branch: mkdocs-enabled-submodules-added @ ${GITHUB_SHA}"
          git branch -M main

          git remote add target https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/simtestlab-se/atlas_deploy.git
          git push --force target main

      # 7️⃣ Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./site
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - ${GITHUB_SHA}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}