name: Mirror Atlas Repo to Private Repo

on:
  push:
    branches:
      - mkdocs-enabled-submodules-added   # only trigger on this branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo A with submodules
      - name: Checkout Repo A (atlas)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ORG_TOKEN }}     # Use organization token for org repo and submodules
          submodules: recursive               # fetch all submodules recursively
          fetch-depth: 0                      # full history if you need it

      # Fallback: Try manual submodule update if checkout fails
      - name: Manual submodule update (fallback)
        if: failure()
        run: |
          git config --global url."https://x-access-token:${{ secrets.ORG_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive || echo "Some submodules failed, continuing..."
        continue-on-error: true

      # Optional: Keep Netlify config files safe
      - name: Preserve Netlify Config
        run: |
          if git clone https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/simtestlab-se/atlas_deploy.git old_repo; then
            echo "Successfully cloned target repo"
            if [ -f "old_repo/netlify.toml" ]; then
              cp old_repo/netlify.toml . 
              echo "Preserved netlify.toml"
            fi
            if [ -f "old_repo/_redirects" ]; then
              cp old_repo/_redirects .
              echo "Preserved _redirects"
            fi
            rm -rf old_repo
          else
            echo "Target repo doesn't exist or is empty, skipping config preservation"
          fi

      # Push snapshot to Repo B
      - name: Push to Repo B
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git config --global init.defaultBranch main

          rm -rf .git
          git init
          git add .
          git commit -m "Mirror from atlas branch: mkdocs-enabled-submodules-added @ ${GITHUB_SHA}"
          git branch -M main

          git remote add target https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/simtestlab-se/atlas_deploy.git
          git push --force target main